**step-1**

**createa dataframe**

- we will create a dataframe using list

- we will create a dataframe using dictionary

In [2]:
import pandas as pd

In [4]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [5]:
type(d1)

pandas.core.frame.DataFrame

**step-2**

**provide the data**

In [9]:
names=['sathish','bhanu','vishwas']
pd.DataFrame(names)

0
0  sathish
1    bhanu
2  vishwas

In [10]:
names=['bhanu','sathish','vishwas']
age=[20,30,40]
data=zip(names,age)
pd.DataFrame(data)

0   1
0    bhanu  20
1  sathish  30
2  vishwas  40

In [11]:
names=['sathish','bhanu','vishwas']
age=[20,21,22]
city=['hyd','ecil','blr']
pd.DataFrame(zip(names,age,city))

0   1     2
0  sathish  20   hyd
1    bhanu  21  ecil
2  vishwas  22   blr

**step-3**

**provide the column names**

In [13]:
names=['sathish','bhanu','vishwas']
pd.DataFrame(names,
             columns=['names'])

names
0  sathish
1    bhanu
2  vishwas

In [15]:
names=['sathish','bhanu','vishwas']
age=[20,21,22]
pd.DataFrame(zip(names,age),
             columns=['names','age'])

names  age
0  sathish   20
1    bhanu   21
2  vishwas   22

In [18]:
names=['sathish','bhanu','vishwas']
age=[20,21,22]
city=['hyd','ecil','blr']

data=zip(names,age,city)

cols=['names','age','city']

pd.DataFrame(data,columns=cols)

names  age  city
0  sathish   20   hyd
1    bhanu   21  ecil
2  vishwas   22   blr

**step-4**

**providing index**

In [20]:
names=['sathish','bhanu','vishwas']
age=[20,21,22]
city=['hyd','ecil','blr']

data=zip(names,age,city)
ix=['A','B','C']  # 3 rows need 3 index
cols=['names','age','city']  # 3 columns , 3 vales

pd.DataFrame(data,
             index=ix,
             columns=cols)

names  age  city
A  sathish   20   hyd
B    bhanu   21  ecil
C  vishwas   22   blr

In [21]:
names=['sathish','bhanu','vishwas']
pd.DataFrame(names)

names=['sathish','bhanu','vishwas']
pd.DataFrame(names,
             columns=['names'])

names=['sathish','bhanu','vishwas']
age=[20,21,22]
pd.DataFrame(zip(names,age),
             columns=['names','age'])


names=['sathish','bhanu','vishwas']
age=[20,21,22]
city=['hyd','ecil','blr']

data=zip(names,age,city)

cols=['names','age','city'] 

pd.DataFrame(data,columns=cols)

names  age  city
0  sathish   20   hyd
1    bhanu   21  ecil
2  vishwas   22   blr

In [32]:
import pandas as pd
name=['sathish','bhanu','vishwas']
age=[20,30,40]
city=['hyd','blr','chn']
data=zip(names,age)
cols=['names','age'] 
pd.DataFrame(data, index=city, columns=cols)


names  age
hyd  sathish   20
blr    bhanu   30
chn  vishwas   40

- create a dataframe

- provide the data

- add the columns

- provide the columns names

- provide the index

In [34]:
import pandas as pd

In [35]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

**step-5**

**add a new column on existing data frame**

In [37]:
# create a dataframe
# name
# age
# city
import pandas as pd
name=['sathish','bhanu','vishwas']
age=[20,30,40]
city=['hyd','blr','ecil']

data=zip(names,age,city)

cols=['names','age','city'] 

df=pd.DataFrame(data,columns=cols)
df


names  age  city
0  sathish   20   hyd
1    bhanu   30   blr
2  vishwas   40  ecil

- if you to add new column
- first check how many rows are there
- for example in above dataframe have 3 rows
- your new column also should have 3 rows
- suppose i want to create a new column: $salary$
- make a list with 3 values
- salary = [1000000,2000000,300000]

$syntax$:dataframe[columns]=list of values

- salary=[100000,2000000,300000]

- df['salary']=salary

In [38]:
df['salary']=[]

ValueError: Length of values (0) does not match length of index (3)

In [40]:
salary=[1000000,200000,300000]
df['salary']=salary
df

names  age  city   salary
0  sathish   20   hyd  1000000
1    bhanu   30   blr   200000
2  vishwas   40  ecil   300000

**case-1**

- create empty data frame first

- create 3 list usingh list comprehesion

- list1= a values from 1 to 10

- list2=square of 1 to 10

- list3=cube of 1 to 10

- finally make a dataframe

In [41]:
import pandas as pd
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [42]:
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]
df1['x']=l1
df1['y']=l2
df1['z']=l3
df1

x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**step-6**

**update the already existed column**

- create a new column
    - creating a new list salary =[1000,2000,3000]
    - df['s']
    - creating a new column the column name is our choice

- update existing column are same way only
    - here also we need a make list values = number of rows
    - while updating the existing column 
    - we need to provide already existing column name only 
    - df['z']= list of values


In [45]:
# data frame name df1
# list of values variables name : z
# which column we want update : z

z=[i**4 for i in range(1,10)]
df1['z']=z
df1

x   y     z
0  1   1     1
1  2   4    16
2  3   9    81
3  4  16   256
4  5  25   625
5  6  36  1296
6  7  49  2401
7  8  64  4096
8  9  81  6561

In [46]:
df2=pd.DataFrame()
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]

df2['number']=l1
df2['square']=l2
df2['cube']=l3

df2

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

**step-7**

**drop the column**

In [47]:
df1.columns

Index(['x', 'y', 'z'], dtype='object')

- if you want to drop a specific column
- we will use drop method
- we already know about difference between keyword and method
- keyword will use directly
- methods will use with corresponding dataframe
**method name:drop**

**df1.drop()**

- column which column you want to drop

- axis:represents the specified value is a row or column

    - axis=0 means rows
    - axis=1 means column
    - by default axis=0

- inplace:will provide overwrite the dataframe or not
    - inplace= True,this indicates overwrite the dataframe
    - inplace =false ,this indicate the modified dataframe will be use when you
       provide new variable for the dataframe

In [48]:
df1.drop('x')
# we are not priding exis
# it assuming the provided values is a row
# by dafult axis=0 ==== rows

KeyError: "['x'] not found in axis"

In [50]:
df1.drop('x',axis=1)

y     z
0   1     1
1   4    16
2   9    81
3  16   256
4  25   625
5  36  1296
6  49  2401
7  64  4096
8  81  6561

In [52]:
df1.drop('x',axis=1,inplace=True)
df1

y     z
0   1     1
1   4    16
2   9    81
3  16   256
4  25   625
5  36  1296
6  49  2401
7  64  4096
8  81  6561

**step-8**

**drop the row**

- drop the column and drop the rows both are similar only

- the only difference axis

    - axis=0 represents rows

    - by dafault axix=0 available

    - which means if we provide any value ,it will represent rows only

In [3]:
# dataframe name:df1
import pandas as pd
df2=pd.DataFrame()
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]

df2['number']=l1
df2['square']=l2
df2['cube']=l3

df2

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [4]:
df2.drop(4)

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [5]:
# multiple rows
# multiple columns keep always in a list
df2.drop([4,8])

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512

In [7]:
df2.columns[[0,1]]

Index(['number', 'square'], dtype='object')

In [8]:
df2.drop([0,1],axis=1)
# [0,1] index
# axis=1  coloumns
# error

KeyError: '[0, 1] not found in axis'

**step-9**

**how to select the column**

In [10]:
df2['square']

# series type 
# no column name display
# whwnever you see this type : series type

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
Name: square, dtype: int64

In [11]:
df2[['square']]
# data frame

square
0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81

In [12]:
type(df2['number'])


pandas.core.series.Series

In [13]:
type(df2[['number']])

pandas.core.frame.DataFrame

In [14]:
df2.number

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: number, dtype: int64

- df2['number']:serirs type
- df2[['number']]:dataframe type
- df2.number:series type

In [15]:
cols=['number','square']
df2[cols]

number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81

In [16]:
df2['number'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

- all values comds in an array
- array means it is a list of elements only represents using numpy package
- generally elements present in 4 ways

    - list : basuc repesentaions
    - numpy array : array with numpy package
    - ternsors : tensorflow package
    - torch : pytorch package

In [6]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [7]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [9]:
#tensor([1,2,3,4,5])

In [10]:
list=[1,2,3,4,]
list2=[10,20,30,40]
list+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [11]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [ ]:
#  3 days every day one 

In [17]:
df2['number']=df2['number'].values
df2

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

**step-10**

**save the dataframe**

- dataframes we can save in two formates

    - csv : comma seperated values

    - xlsx : excel format 

- i order to save any data

    - where you want to save : dictioranary name

    - what is the name of the file for storing name

    - what is the extension

- we already seen in file handling session

In [ ]:
# case-1 : saving file at same location
# no need to provide directory path
# directory give only name of the file
# and extension

In [21]:
# dataframe  name : df2
df2.to_csv('Data1.csv')
df2.to_excel('Data1.xlsx') 


**step-11 how to read a dataframe**

In [22]:
import pandas as pd
pd.read_csv('data1.csv')

Unnamed: 0  number  square  cube
0           0       1       1     1
1           1       2       4     8
2           2       3       9    27
3           3       4      16    64
4           4       5      25   125
5           5       6      36   216
6           6       7      49   343
7           7       8      64   512
8           8       9      81   729

In [23]:
import os
os.getcwd()

'C:\\Users\\sathish\\Documents\\sathish'

In [26]:
import pandas as pd
pd.read_excel('Data1.xlsx')

Unnamed: 0  number  square  cube
0           0       1       1     1
1           1       2       4     8
2           2       3       9    27
3           3       4      16    64
4           4       5      25   125
5           5       6      36   216
6           6       7      49   343
7           7       8      64   512
8           8       9      81   729

**step-12:**

**How to avoid index column**

- while we save the dataframe

- automatically a new column will create

- that we need to avoid

- permission denied means close the data file from laptop

In [27]:
# dataframe name:df2
# save the data with out index column
df2.to_csv('Data1.csv',index=False)
df2.to_excel('Data1.xlsx',index=False)

In [28]:
# read the data
import pandas as pd
pd.read_csv('Data1.csv')


number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729